services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql:Z
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass password 
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
