name: Go CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v.*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.3']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      
      - name: Download go dependencies
        run: go mod Download
      
      - name: Verify go dependencies
        run: go mod verify

      - name: Build
        run: go build -v .


  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.3'] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true 

    - name: Download Go modules (for test job)
      run: go mod download

    - name: Run tests
      run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic 

    - name: Lint (Optional, but recommended)
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59.1 
        args: --timeout=5m

  build-image:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up docker buildx
        uses: docker/setup-buildx-actions@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: indigowar/weatherapp
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
            type=sha,format=long,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            # You can add more tags here if needed, e.g., type=ref,event=branch
      
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max